### ISSUE TITLE
mqtt example not compatible with python3/unicode, quick fix

### ISSUE THREAD

**Issue by BeauSlim** [pimoroni/blinkt#78]
I had to change the one line from 
`data = msg.payload.split(',')`
to 
`data = msg.payload.decode("utf-8").split(',')` for it to work.

**Comment by Gadgetoid** [comment]
Hopefully fixed in a back-compatible (although Python 2 is EOL anyway) way. Thanks for reporting!

**Comment by V1d1o7** [comment]
This is still an issue running on a Pi Zero W running Raspberry Pi OS (32bit) 2022-01-28. Super happy I came across this, thanks @BeauSlim!

**Comment by V1d1o7** [comment]
Upon further investigation, it looks like the bash script may need a small tweak, or the repo it self needs to be adjusted to download the correct "version" of the files.
